color0 #121212
color1 #b14242
color2 #737373
color3 #e5a72a
color4 #4a8b8b
color5 #d87c4a
color6 #d5d5d5
color7 #b4b4b4
color8 #535353
color9 #df6464
color10 #a7a7a7
color11 #e49a44
color12 #4a8b8b
color13 #c4693d
color14 #e5e5e5
color15 #e5e5e5

cursor                #c4693d
cursor_text_color     #121212
background            #121212
foreground            #b4b4b4
selection_foreground  #e5e5e5
selection_background  #322119
active_border_color   #c4693d
inactive_border_color #1d1d1d
url_color             #c4693d

active_tab_foreground   #121212
active_tab_background   #c4693d
inactive_tab_foreground #d5d5d5
inactive_tab_background #1d1d1d
cursor_trail_color      #d5d5d5
