$background = rgb(1a1110)
$foreground = rgb(d8c2bf)
$color0 = rgb(e20815)
$color1 = rgb(ffb4aa)
$color2 = rgb(ffb4aa)
$color3 = rgb(ffb4aa)
$color4 = rgb(ffb4aa)
$color5 = rgb(ffb4aa)
$color6 = rgb(e7bdb7)
$color7 = rgb(e7bdb7)
$color11 = rgb(e7bdb7)
$color12 = rgb(e7bdb7)
$color13 = rgb(e7bdb7)
$color14 = rgb(e7bdb7)
$color15 = rgb(e7bdb7)
