$background = rgb(141314)
$foreground = rgb(c9c5cb)
$color0 = rgb(0a090e)
$color1 = rgb(c9c5cc)
$color2 = rgb(c9c5cc)
$color3 = rgb(c9c5cc)
$color4 = rgb(c9c5cc)
$color5 = rgb(c9c5cc)
$color6 = rgb(c9c5c8)
$color7 = rgb(c9c5c8)
$color11 = rgb(c9c5c8)
$color12 = rgb(c9c5c8)
$color13 = rgb(c9c5c8)
$color14 = rgb(c9c5c8)
$color15 = rgb(c9c5c8)
