-- Generated by hyprconf2lua v1.4.0
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

-- source = $HOME/.config/hypr/wallust/wallust-hyprland.conf -> requires manual conversion
-- local wallust-hyprland = require("wallust-hyprland")
-- TODO: convert $HOME/.config/hypr/wallust/wallust-hyprland.conf to .lua and use require()

hl.config({
    dwindle = {
        pseudotile = true,
        preserve_split = true,
        special_scale_factor = 0.8,
    },
})

hl.config({
    master = {
        new_status = "slave",
        new_on_top = 1,
        mfact = 0.5,
    },
})

hl.config({
    general = {
        border_size = 0,
        resize_on_border = true,
        layout = "master",
        gaps_out = 20,
        gaps_in = 1,
        snap = {
            border_overlap = true,
        },
        col = {
            active_border = color1,
            inactive_border = color0,
        },
    },
})

hl.config({
    decoration = {
        rounding = 0,
        active_opacity = 1.0,
        inactive_opacity = 1.0,
        fullscreen_opacity = 1.0,
        dim_inactive = true,
        dim_strength = 0.2,
        dim_special = 0.8,
        shadow = {
            enabled = false,
            sharp = false,
            color = color0,
            range = 20,
        },
        blur = {
            enabled = false,
            passes = 2,
            size = 4,
            xray = false,
        },
    },
})

hl.config({
    input = {
        kb_layout = "us",
        kb_variant = {  },
        kb_model = {  },
        kb_options = {  },
        kb_rules = {  },
        repeat_rate = 50,
        repeat_delay = 300,
        numlock_by_default = true,
        left_handed = false,
        follow_mouse = true,
        float_switch_override_focus = false,
        touchpad = {
            disable_while_typing = true,
            natural_scroll = true,
            clickfinger_behavior = false,
            middle_button_emulation = true,
            tap-to-click = true,
            drag_lock = false,
        },
        touchdevice = {
            enabled = true,
        },
        tablet = {
            transform = 0,
            left_handed = 0,
        },
    },
})

hl.config({
    gestures = {
        workspace_swipe = true,
        workspace_swipe_fingers = 3,
        workspace_swipe_distance = 500,
        workspace_swipe_invert = true,
        workspace_swipe_min_speed_to_force = 30,
        workspace_swipe_cancel_ratio = 0.5,
        workspace_swipe_create_new = true,
        workspace_swipe_forever = true,
    },
})

hl.config({
    group = {
        groupbar = {
            col.active = color1,
            height = 20,
        },
        col = {
            border_active = color15,
        },
    },
})

hl.config({
    misc = {
        disable_hyprland_logo = true,
        enable_anr_dialog = "false;",
        disable_splash_rendering = true,
        vfr = true,
        mouse_move_enables_dpms = true,
        enable_swallow = true,
        focus_on_activate = false,
        initial_workspace_tracking = 0,
        middle_click_paste = false,
    },
})

hl.config({
    render = {
        direct_scanout = false,
    },
})

hl.config({
    binds = {
        workspace_back_and_forth = true,
        allow_workspace_cycles = true,
        pass_mouse_when_bound = false,
    },
})

hl.config({
    xwayland = {
        force_zero_scaling = true,
    },
})

hl.config({
    cursor = {
        no_hardware_cursors = false,
        enable_hyprcursor = true,
        warp_on_change_workspace = false,
        no_warps = true,
    },
})

hl.config({
    animations = {
        enabled = true,
    },
})

hl.plugin("hyprbars", function()
    bar_height = 25,
    bar_text_font = "Iosevka Bold Italic",
    bar_text_size = 15,
    bar_text_align = "left",
    -- hyprbars-button = rgb(ff4040), 10, 󰖭, hyprctl dispatch killactive
end)
hl.plugin("hyprscrolling", function()
    column_width = 0.9,
end)
hl.plugin("hyprtrails", function()
    color = color0,
end)
