-- Generated by hyprconf2lua v1.4.0
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

require("keybinds")
require("window-rules")
require("config")


hl.env("CLUTTER_BACKEND", "wayland")

hl.env("GDK_BACKEND", "wayland,x11")

hl.env("QT_AUTO_SCREEN_SCALE_FACTOR", 1)

hl.env("QT_QPA_PLATFORM", "wayland;xcb")

hl.env("QT_QPA_PLATFORMTHEME", "qt6ct")

hl.env("QT_SCALE_FACTOR", 1)

hl.env("QT_WAYLAND_DISABLE_WINDOWDECORATION", 1)

hl.env("XDG_CURRENT_DESKTOP", "Hyprland")

hl.env("XDG_SESSION_DESKTOP", "Hyprland")

hl.env("XDG_SESSION_TYPE", "wayland")

hl.env("MOZ_ENABLE_WAYLAND", 1)

hl.env("ELECTRON_OZONE_PLATFORM_HINT", "auto")

hl.monitor({
  output   = "eDP-1",
  mode     = "preferred",
  position = "auto",
  scale    = 1.25,
})

hl.monitor({
  output   = "HDMI-A-1",
  mode     = "preferred",
  position = "auto",
  scale    = 2,
})

hl.config({
  debug = {
    suppress_errors = true,
  },
})

-- Autostart
hl.on("hyprland.start", function()
  hl.exec_cmd("dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP")
  hl.exec_cmd("systemctl --user import-environment WAYLAND_DISPLAY XDG_CURRENT_DESKTOP")
  hl.exec_cmd("systemctl --user start hyprpolkitagent")
  hl.exec_cmd("nm-applet --indicator &")
  hl.exec_cmd("wl-paste --type text --watch cliphist store")
  hl.exec_cmd("wl-paste --type image --watch cliphist store")
  hl.exec_cmd("noctalia")

end)

-- Exec (run every reload)
hl.on("config.reloaded", function()
  hl.exec_cmd("hyprctl setcursor Layan-cursors 10")
end)
