-- Generated by hyprconf2lua v1.4.0
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

local mainMod = "SUPER"

local scriptsDir = "local_var_HOME/.config/hypr/scripts"

local UserScripts = "local_var_HOME/.config/hypr/UserScripts"

hl.bind("CTRL + ALT" .. " + " .. "Delete", hl.dsp.exec_cmd("hyprctl dispatch exit 0"))

hl.bind(mainMod .. " + " .. "Q", hl.dsp.window.close())

hl.bind(mainMod .. " + " .. "F", hl.dsp.window.fullscreen())

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "F", hl.dsp.window.float())

hl.bind(mainMod .. " + " .. "ALT" .. " + " .. "F", hl.dsp.exec_cmd("hyprctl dispatch workspaceopt allfloat"))

--hack

hl.bind(mainMod .. " + " .. "B", hl.dsp.exec_cmd("eww open topbar_laptop --toggle"))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "B", hl.dsp.exec_cmd("eww open music --toggle"))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "D", hl.dsp.layout("removemaster"))

hl.bind(mainMod .. " + " .. "N", hl.dsp.exec_cmd("rofi-connman"))

hl.bind(mainMod .. " + " .. "I", hl.dsp.layout("addmaster"))

hl.bind(mainMod .. " + " .. "J", hl.dsp.layout("cyclenext"))

hl.bind(mainMod .. " + " .. "K", hl.dsp.layout("cycleprev"))

hl.bind(mainMod .. " + " .. "M", hl.dsp.exec_cmd("hyprctl dispatch splitratio 0.2"))

hl.bind(mainMod .. " + " .. "V", hl.dsp.exec_cmd("hyprctl -- dispatch splitratio -0.2"))

hl.bind(mainMod .. " + " .. "P", hl.dsp.layout("swapwithmaster"))

hl.bind(mainMod .. " + " .. "C", hl.dsp.layout("orientationcenter"))

hl.bind(mainMod .. " + " .. "C", hl.dsp.exec_cmd("hyprctl keyword general:gaps_in 1"))

hl.bind(mainMod .. " + " .. "L", hl.dsp.layout("orientationleft"))

hl.bind(mainMod .. " + " .. "L", hl.dsp.exec_cmd("hyprctl keyword general:gaps_in 5"))

hl.bind(mainMod .. " + " .. "G", hl.dsp.group.toggle())

hl.bind(mainMod .. " + " .. "RIGHT", hl.dsp.group.next())

hl.bind(mainMod .. " + " .. "LEFT", hl.dsp.group.next({ forward = false }))

hl.bind(mainMod .. " + " .. "DOWN", hl.dsp.window.move({ out_of_group = true }))

hl.bind(mainMod .. " + " .. "UP", hl.dsp.window.move({ into_group = "left" }))

hl.bind("ALT" .. " + " .. "Tab", hl.dsp.window.cycle_next())

-- TODO: manual review (unknown dispatcher: bringactivetotop)
-- hl.bind("ALT + Tab", hl.dsp.bringactivetotop())

hl.bind("xf86audioraisevolume", hl.dsp.exec_cmd("local_var_HOME/.config/hypr/scripts/Volume.sh inc"), { locked = true })

hl.bind("xf86audiolowervolume", hl.dsp.exec_cmd("local_var_HOME/.config/hypr/scripts/Volume.sh dec"), { locked = true })

hl.bind("xf86Sleep", hl.dsp.exec_cmd("systemctl suspend"), { locked = true })

hl.bind("xf86AudioPlay", hl.dsp.exec_cmd("local_var_HOME/.config/hypr/scripts/MediaCtrl.sh pause"), { locked = true })

hl.bind("xf86AudioNext", hl.dsp.exec_cmd("local_var_HOME/.config/hypr/scripts/MediaCtrl.sh next"), { locked = true })

hl.bind("xf86AudioPrev", hl.dsp.exec_cmd("local_var_HOME/.config/hypr/scripts/MediaCtrl.sh prev"), { locked = true })

hl.bind("xf86audiostop", hl.dsp.exec_cmd("local_var_HOME/.config/hypr/scripts/MediaCtrl.sh stop"), { locked = true })

hl.bind(mainMod .. " + " .. "Print", hl.dsp.exec_cmd("local_var_HOME/.config/hypr/scripts/ScreenShot.sh"))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "Print", hl.dsp.exec_cmd("local_var_HOME/.config/hypr/scripts/ScreenShot.sh r"))

-- TODO: manual review (unknown dispatcher: resizeactive)
-- hl.bind("$mainMod + SHIFT + left", hl.dsp.resizeactive("-50 0"))

-- TODO: manual review (unknown dispatcher: resizeactive)
-- hl.bind("$mainMod + SHIFT + right", hl.dsp.resizeactive("50 0"))

-- TODO: manual review (unknown dispatcher: resizeactive)
-- hl.bind("$mainMod + SHIFT + up", hl.dsp.resizeactive("0 -50"))

-- TODO: manual review (unknown dispatcher: resizeactive)
-- hl.bind("$mainMod + SHIFT + down", hl.dsp.resizeactive("0 50"))

-- TODO: manual review (unknown dispatcher: resizeactive)
-- hl.bind("$mainMod + SHIFT + SPACE", hl.dsp.resizeactive("exact 60% 60%"))

hl.bind(mainMod .. " + " .. "CTRL" .. " + " .. "left", { direction = "l" })

hl.bind(mainMod .. " + " .. "CTRL" .. " + " .. "right", { direction = "r" })

hl.bind(mainMod .. " + " .. "CTRL" .. " + " .. "up", { direction = "u" })

hl.bind(mainMod .. " + " .. "CTRL" .. " + " .. "down", { direction = "d" })

hl.bind(mainMod .. " + " .. "left", hl.dsp.focus({ direction = "left" }))

hl.bind(mainMod .. " + " .. "right", hl.dsp.focus({ direction = "right" }))

hl.bind(mainMod .. " + " .. "up", hl.dsp.focus({ direction = "up" }))

hl.bind(mainMod .. " + " .. "down", hl.dsp.focus({ direction = "down" }))

hl.bind(mainMod .. " + " .. "tab", hl.dsp.focus({ workspace = "m+1" }))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "tab", hl.dsp.focus({ workspace = "m-1" }))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "U", hl.dsp.window.move({ workspace = "special" }))

hl.bind(mainMod .. " + " .. "U", hl.dsp.workspace.toggle_special(nil))

hl.bind(mainMod .. " + " .. "code:10", hl.dsp.focus({ workspace = 1 }))

hl.bind(mainMod .. " + " .. "code:11", hl.dsp.focus({ workspace = 2 }))

hl.bind(mainMod .. " + " .. "code:12", hl.dsp.focus({ workspace = 3 }))

hl.bind(mainMod .. " + " .. "code:13", hl.dsp.focus({ workspace = 4 }))

hl.bind(mainMod .. " + " .. "code:14", hl.dsp.focus({ workspace = 5 }))

hl.bind(mainMod .. " + " .. "code:15", hl.dsp.focus({ workspace = 6 }))

hl.bind(mainMod .. " + " .. "code:16", hl.dsp.focus({ workspace = 7 }))

hl.bind(mainMod .. " + " .. "code:17", hl.dsp.focus({ workspace = 8 }))

hl.bind(mainMod .. " + " .. "code:18", hl.dsp.focus({ workspace = 9 }))

hl.bind(mainMod .. " + " .. "code:19", hl.dsp.focus({ workspace = 10 }))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "code:10", hl.dsp.window.move({ workspace = 1 }))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "code:11", hl.dsp.window.move({ workspace = 2 }))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "code:12", hl.dsp.window.move({ workspace = 3 }))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "code:13", hl.dsp.window.move({ workspace = 4 }))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "code:14", hl.dsp.window.move({ workspace = 5 }))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "code:15", hl.dsp.window.move({ workspace = 6 }))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "code:16", hl.dsp.window.move({ workspace = 7 }))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "code:17", hl.dsp.window.move({ workspace = 8 }))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "code:18", hl.dsp.window.move({ workspace = 9 }))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "code:19", hl.dsp.window.move({ workspace = 10 }))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "bracketleft", hl.dsp.window.move({ direction = -1 }))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "bracketright", hl.dsp.window.move({ direction = "+1" }))

hl.bind(mainMod .. " + " .. "CTRL" .. " + " .. "code:10", hl.dsp.window.move({ workspace = 1 }, { follow = false }))

hl.bind(mainMod .. " + " .. "CTRL" .. " + " .. "code:11", hl.dsp.window.move({ workspace = 2 }, { follow = false }))

hl.bind(mainMod .. " + " .. "CTRL" .. " + " .. "code:12", hl.dsp.window.move({ workspace = 3 }, { follow = false }))

hl.bind(mainMod .. " + " .. "CTRL" .. " + " .. "code:13", hl.dsp.window.move({ workspace = 4 }, { follow = false }))

hl.bind(mainMod .. " + " .. "CTRL" .. " + " .. "code:14", hl.dsp.window.move({ workspace = 5 }, { follow = false }))

hl.bind(mainMod .. " + " .. "CTRL" .. " + " .. "code:15", hl.dsp.window.move({ workspace = 6 }, { follow = false }))

hl.bind(mainMod .. " + " .. "CTRL" .. " + " .. "code:16", hl.dsp.window.move({ workspace = 7 }, { follow = false }))

hl.bind(mainMod .. " + " .. "CTRL" .. " + " .. "code:17", hl.dsp.window.move({ workspace = 8 }, { follow = false }))

hl.bind(mainMod .. " + " .. "CTRL" .. " + " .. "code:18", hl.dsp.window.move({ workspace = 9 }, { follow = false }))

hl.bind(mainMod .. " + " .. "CTRL" .. " + " .. "code:19", hl.dsp.window.move({ workspace = 10 }, { follow = false }))

hl.bind(mainMod .. " + " .. "CTRL" .. " + " .. "bracketleft", hl.dsp.window.move({ direction = -1 }, { follow = false }))

hl.bind(mainMod .. " + " .. "CTRL" .. " + " .. "bracketright", hl.dsp.window.move({ direction = "+1" }, { follow = false }))

hl.bind(mainMod .. " + " .. "mouse_down", hl.dsp.focus({ workspace = "e+1" }))

hl.bind(mainMod .. " + " .. "mouse_up", hl.dsp.focus({ workspace = "e-1" }))

hl.bind(mainMod .. " + " .. "period", hl.dsp.focus({ workspace = "e+1" }))

hl.bind(mainMod .. " + " .. "comma", hl.dsp.focus({ workspace = "e-1" }))

hl.bind(mainMod .. " + " .. "mouse:272", hl.dsp.window.drag(), { mouse = true })

hl.bind(mainMod .. " + " .. "mouse:273", hl.dsp.window.resize(), { mouse = true })

hl.bind("xf86MonBrightnessDown", hl.dsp.exec_cmd("local_var_HOME/.config/hypr/scripts/Brightness.sh dec 3"))

hl.bind("xf86MonBrightnessUp", hl.dsp.exec_cmd("local_var_HOME/.config/hypr/scripts/Brightness.sh inc 3"))

hl.bind("xf86TouchpadToggle", hl.dsp.exec_cmd("local_var_HOME/.config/hypr/scripts/TouchPad.sh"))

hl.bind(mainMod .. " + " .. "F6", hl.dsp.exec_cmd("local_var_HOME/.config/hypr/scripts/ScreenShot.sh --now"))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "F6", hl.dsp.exec_cmd("local_var_HOME/.config/hypr/scripts/ScreenShot.sh --area"))

hl.bind(mainMod .. " + " .. "CTRL" .. " + " .. "F6", hl.dsp.exec_cmd("local_var_HOME/.config/hypr/scripts/ScreenShot.sh --in5"))

hl.bind(mainMod .. " + " .. "ALT" .. " + " .. "F6", hl.dsp.exec_cmd("local_var_HOME/.config/hypr/scripts/ScreenShot.sh --in10"))

hl.bind("ALT" .. " + " .. "F6", hl.dsp.exec_cmd("local_var_HOME/.config/hypr/scripts/ScreenShot.sh --active"))

local TOUCHPAD_ENABLED = true

hl.device({
    name = "$Touchpad_Device",
    enabled = true,
})

local files = "thunar"

local term = "kitty"

local scriptsDir = "local_var_HOME/.config/hypr/scripts"

local UserScripts = "local_var_HOME/.config/hypr/UserScripts"

hl.bind(mainMod .. " + " .. "D", hl.dsp.exec_cmd("pkill rofi || rofi -show drun -modi drun,filebrowser,run,window"))

hl.bind("ALT" .. " + " .. "D", hl.dsp.exec_cmd("pkill rofi || rofi -show window"))

hl.bind(mainMod .. " + " .. "Return", hl.dsp.exec_cmd("kitty"))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "Return", hl.dsp.exec_cmd("kitty --class=floating.term"))

hl.bind(mainMod .. " + " .. "T", hl.dsp.exec_cmd("thunar"))

hl.bind(mainMod .. " + " .. "O", hl.dsp.exec_cmd("firefox"))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "Return", hl.dsp.exec_cmd("pypr toggle term"))

hl.bind(mainMod .. " + " .. "Z", hl.dsp.exec_cmd("pypr zoom"))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "P", hl.dsp.exec_cmd("swww restore"))

hl.bind("KP_End", hl.dsp.focus({ workspace = 1 }))

hl.bind("KP_Down", hl.dsp.focus({ workspace = 2 }))

hl.bind("KP_Next", hl.dsp.focus({ workspace = 3 }))

hl.bind("KP_Left", hl.dsp.focus({ workspace = 4 }))

hl.bind("KP_Begin", hl.dsp.focus({ workspace = 5 }))

hl.bind("KP_Right", hl.dsp.focus({ workspace = 6 }))

hl.bind("KP_Home", hl.dsp.focus({ workspace = 7 }))

hl.bind("KP_Up", hl.dsp.focus({ workspace = 8 }))

hl.bind("KP_Prior", hl.dsp.focus({ workspace = 9 }))

hl.bind("KP_Insert", hl.dsp.focus({ workspace = 10 }))

hl.bind(mainMod .. " + " .. "KP_End", hl.dsp.window.move({ workspace = 1 }))

hl.bind(mainMod .. " + " .. "KP_Down", hl.dsp.window.move({ workspace = 2 }))

hl.bind(mainMod .. " + " .. "KP_Next", hl.dsp.window.move({ workspace = 3 }))

hl.bind(mainMod .. " + " .. "KP_Left", hl.dsp.window.move({ workspace = 4 }))

hl.bind(mainMod .. " + " .. "KP_Begin", hl.dsp.window.move({ workspace = 5 }))

hl.bind(mainMod .. " + " .. "KP_Right", hl.dsp.window.move({ workspace = 6 }))

hl.bind(mainMod .. " + " .. "KP_Home", hl.dsp.window.move({ workspace = 7 }))

hl.bind(mainMod .. " + " .. "KP_Up", hl.dsp.window.move({ workspace = 8 }))

hl.bind(mainMod .. " + " .. "KP_Prior", hl.dsp.window.move({ workspace = 9 }))

hl.bind(mainMod .. " + " .. "KP_Insert", hl.dsp.window.move({ workspace = 10 }))

-- HYPRSCROLLER

-- bind = $mainMod, J, scroller:jump

-- bind = $mainMod, C, scroller:fitsize, active

hl.bind(mainMod .. " + " .. "Shift" .. " + " .. "P", hl.dsp.exec_cmd("local_var_HOME/.config/hypr/scripts/choose_accent.sh"))

hl.bind(mainMod .. " + " .. "Shift" .. " + " .. "Right", hl.dsp.layout("move +col"))
