-- Generated by hyprconf2lua v1.4.0
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

hl.window_rule({
    name  = "size_60__60_",
    match = {
        class = "(fdm|neohtop)",
    },
    size = "60% 60%",
})

hl.window_rule({
    name  = "workspace_10",
    match = {
        title = "(Display Window)",
    },
    workspace = 10,
})

hl.window_rule({
    name  = "size_60__60_",
    match = {
        title = "(Select one or multiple files)",
    },
    size = "60% 60%",
})

hl.window_rule({
    name  = "float",
    match = {
        class = "(swengine.desktop)",
    },
    float = true,
})

hl.layer_rule({
    match = {
        namespace = "topbar",
    },
    blur = true,
})

hl.window_rule({
    name  = "workspace_3_silent",
    match = {
        class = "(Spotify)",
    },
    workspace = "3 silent",
})

hl.window_rule({
    name  = "workspace_2",
    match = {
        class = "(brave-browser|firefox|Vivaldi-stable)",
    },
    workspace = 2,
})

hl.window_rule({
    name  = "workspace_5",
    match = {
        class = "(thunar)",
    },
    workspace = 5,
})

hl.window_rule({
    name  = "float",
    match = {
        class = "(floating.term)",
    },
    float = true,
})

hl.window_rule({
    name  = "float",
    match = {
        class = "(code-url-handler)",
    },
    float = true,
})

hl.window_rule({
    name  = "size_90__90_",
    match = {
        class = "(code-url-handler)",
    },
    size = "90% 90%",
})

hl.window_rule({
    name  = "size_70__70_",
    match = {
        title = "(Simple Preferences|Open subtitles)",
    },
    size = "70% 70%",
})

hl.window_rule({
    name  = "size_819_479",
    match = {
        class = "(floating.term)",
    },
    size = "819 479",
})

hl.window_rule({
    name  = "move_279_142",
    match = {
        class = "(floating.term)",
    },
    move = "279 142",
})

hl.window_rule({
    name  = "size_1166_618",
    match = {
        class = "(kitty)",
    },
    size = "1166 618",
})

hl.window_rule({
    name  = "noblur",
    match = {
        title = "",
    },
    blur = false,
})

hl.window_rule({
    name  = "float",
    match = {
        class = "(fdm|org.gnome.SystemMonitor)",
    },
    float = true,
})

hl.window_rule({
    name  = "float",
    match = {
        title = "(.*)(Vivaldi Settings:)",
    },
    float = true,
})

hl.window_rule({
    name  = "opacity_0_9",
    match = {
        class = "(Spotify|firefox)",
    },
    opacity = 0.9,
})
