cursor #e5e1e2
cursor_text_color #c9c5cb

foreground            #e5e1e2
background            #141314
selection_foreground  #313032
selection_background  #c9c5c8
url_color             #c9c5cc

# black
color8   #262626
color0   #4c4c4c

# red
color1   #0a090e
color9   #c49ea0

# green
color2   #8aac8b
color10  #9ec49f

# yellow
color3   #c9c5cc
color11  #c4c19e

# blue
/* color4  #8f8aac */
color4  #c9c5cc
color12 #a39ec4

# magenta
color5   #ac8aac
color13  #c49ec4

# cyan
color6   #8aacab
color14  #9ec3c4

# white
color15   #e7e7e7
color7  #f0f0f0
