[audio]
enable_sounds = true
sound_volume = 0.99999997764825821

[backdrop]
blur_intensity = 0.7799999825656414
enabled = true

[bar.default]
capsule = true
capsule_opacity = 0.5599999874830246
end = [ "audio_visualizer", "tray", "network", "battery" ]
font_weight = 380
margin_edge = 5
margin_ends = 5
padding = 0
position = "right"
radius = 14
scale = 1.300000011920929
start = [ "workspaces", "sysmon" ]
thickness = 37
widget_spacing = 5

[[control_center.shortcuts]]
type = "wifi"

[[control_center.shortcuts]]
type = "bluetooth"

[[control_center.shortcuts]]
type = "caffeine"

[[control_center.shortcuts]]
type = "nightlight"

[[control_center.shortcuts]]
type = "notification"

[desktop_widgets]
schema_version = 1
widget_order = [ "desktop-widget-0000000000000002", "desktop-widget-0000000000000001" ]

    [desktop_widgets.grid]
    cell_size = 8
    major_interval = 4
    visible = true

    [desktop_widgets.widget.desktop-widget-0000000000000001]
    box_height = 160.0
    box_width = 376.0
    cx = 244.0
    cy = 736.0
    output = "eDP-1"
    rotation = 0.0
    type = "media_player"

        [desktop_widgets.widget.desktop-widget-0000000000000001.settings]
        background = true
        background_color = "surface"
        background_opacity = 1.0
        background_padding = 13.0
        background_radius = 11.0
        hide_when_no_media = true
        layout = "horizontal"

    [desktop_widgets.widget.desktop-widget-0000000000000002]
    box_height = 440.0
    box_width = 1056.0
    cx = 528.0
    cy = 88.0
    flip_y = true
    output = "eDP-1"
    rotation = 0.0
    type = "audio_visualizer"

        [desktop_widgets.widget.desktop-widget-0000000000000002.settings]
        aspect_ratio = 6.0
        background = false
        background_opacity = 0.029999999999999999
        background_padding = 0.0
        background_radius = 0.0
        bands = 32.0
        centered = true
        color_1 = "tertiary"
        high_color = "error"
        low_color = "primary"
        mirrored = true
        show_when_idle = false

[dock]
icon_size = 20
launcher_position = "start"

[lockscreen_widgets]
enabled = false
schema_version = 2
widget_order = [ "lockscreen-login-box@eDP-1" ]

    [lockscreen_widgets.grid]
    cell_size = 16
    major_interval = 4
    visible = true

    [lockscreen_widgets.widget."lockscreen-login-box@eDP-1"]
    box_height = 0.0
    box_width = 0.0
    cx = 768.0
    cy = 741.0
    output = "eDP-1"
    rotation = 0.0
    type = "login_box"

[nightlight]
enabled = true

[osd]
background_opacity = 0.99999997764825821
lock_keys = false
position = "bottom_right"

    [osd.kinds]
    lock_keys = false

[plugin_settings."noctalia/screen_recorder"]
video_source = "portal"

[plugins]
enabled = [ "noctalia/screen_recorder", "noctalia/example" ]

    [[plugins.source]]
    kind = "git"
    location = "https://github.com/noctalia-dev/official-plugins"
    name = "official"

    [[plugins.source]]
    kind = "git"
    location = "https://github.com/noctalia-dev/community-plugins"
    name = "community"

[shell]
avatar_path = "/home/noble/takavic.jpg"
font_family = "CaskaydiaCove Nerd Font"
polkit_agent = true
settings_show_advanced = true
ui_scale = 1.25

    [shell.panel]
    control_center_placement = "centered"
    session_placement = "centered"

[theme]
builtin = "Catppuccin"
community_palette = "Cyberpunk"
mode = "dark"
source = "community"
wallpaper_scheme = "m3-tonal-spot"

    [theme.templates]
    builtin_ids = [ "gtk3", "gtk4", "helix", "kitty", "niri", "qt" ]
    community_ids = [ "spicetify", "zed" ]

[wallpaper]
directory = "/home/noble/Pictures/Wallpapers"

    [wallpaper.default]
    path = "/home/noble/Pictures/Wallpapers/wallhaven-4d8vzg.jpg"

    [wallpaper.last]
    path = "/home/noble/Pictures/Wallpapers/wallhaven-4d8vzg.jpg"

    [wallpaper.monitors.eDP-1]
    path = "/home/noble/Pictures/Wallpapers/wallhaven-4d8vzg.jpg"

[widget.battery]
show_label = false

[widget.brightness]
show_label = false

[widget.clock]
format = "{:%H:%M - %d:%m}"

[widget.hello]
type = "noctalia/example:hello"

[widget.network]
show_label = false

[widget.nirilogo]
font_weight = 100
glyph = "niri"
scale = 1.1000000000000001
type = "custom_button"

[widget.recorder]
type = "noctalia/screen_recorder:recorder"

[widget.s]
type = "spacer"

[widget.screen_recorder]
script = "scripts/screen_recorder.lua"
type = "scripted"
video_source = "portal"

[widget.sysmon]
show_label = false
stat = "ram_used"

[widget.taskbar]
group_by_workspace = true
hide_empty_workspaces = true
scale = 0.75

[widget.volume]
show_label = false

[widget.workspaces]
hide_when_empty = true