theme="peachpuff"
[editor.soft-wrap]
enable=true

[editor.cursor-shape]
insert="bar"
normal="block"
select="underline"

[editor]
color-modes=true
# line-number="relative"
gutters = ["diagnostics", "spacer", "diff"]
shell=["nu", "--stdin","-c"]

[editor.statusline]
separator="|"
mode.normal="NORMAL"
mode.insert="INSERT"
mode.select="VISUAL"
# right = [ "diagnostics", "position","file-name"]
# center=[]
# left=[]
# right=[]
# center=[]


[editor.lsp]
display-inlay-hints = true
auto-signature-help = false

[editor.inline-diagnostics]
cursor-line="warning"


